### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-risk#100]
This issue was created to capture the continuous release notes. Insight from comments will be used to create the regular release note.

Example comments could be:

    name of new metric and date of release
    descriptions of changes to existing metric
    Changes to focus areas or restructuring of WG

**Comment by GeorgLink** [comment]
I would appreciate if we could include the fix to the elephant factor in the next release #101

**Comment by klumb** [comment]
@GeorgLink this release?

**Comment by GeorgLink** [comment]
yes, this release, sorry.

**Comment by klumb** [comment]
issue #102 will collect comments for Elephant factor - need to add the disclaimer to the metric markdown.

**Comment by sgoggins** [comment]
@klumb : Remind me about the disclaimer ...

**Comment by klumb** [comment]
Closing for release 2020-08
