### ISSUE TITLE
Release Candidate Comments (Elephant Factor) 

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-risk#102]
This issue was created to collect comments about the upcoming metrics release.

This thread is for comments about Elephant Factor

GitHub location: https://github.com/chaoss/wg-risk/blob/master/metrics/Elephant_Factor.md

See all release candidates of metrics are at:
https://chaoss.community/metrics-202008/

**Comment by klumb** [comment]
PR edit was #101

**Comment by foundjem** [comment]
LGTM after correcting the formula for computing the  Elephant Factor.

Signed-off-by: Armstrong <foundjem@ieee.org>

**Comment by klumb** [comment]
@sgoggins can this be closed?

**Comment by sgoggins** [comment]
@klumb : Yes.
