### ISSUE TITLE
Release Notes - 2021-02

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-risk#108]
This issue was created to capture the continuous contribution notes. Insight from comments will be used to create the regular release note.

Example comments could be:

name of new metric and date of release
descriptions of changes to existing metric
Changes to focus areas or restructuring of WG

**Comment by klumb** [comment]
SPDX Metric
GitHub location: https://github.com/chaoss/wg-risk/blob/master/metrics/SPDX_Document.md
https://github.com/chaoss/wg-risk/issues/106

Live on the website - 08--08-2020

**Comment by germonprez** [comment]
Adding Bus Factor: 
https://github.com/chaoss/wg-risk/blob/master/metrics/Bus_Factor.md

This goes into the latest release

**Comment by klumb** [comment]
Closing for release 2021-03
