### ISSUE TITLE
Add GrimoireLab Visualization to License Metrics

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-risk#13]
We started discussing in #12 that GrimoireLab is currently implementing new visualizations for license information. 

This issue is for adding information to the License metrics about how to find the license information in GrimoireLab (see [example for what this could look like in the Evolution WG](https://github.com/chaoss/wg-evolution/blob/master/metrics/Code_Changes_Lines.md#known-implementations)).

@inishchith and @valeriocos It would be great if you could, during the next two weeks, add some information for what is currently possible with GrimoireLab to the Risk WG metrics. It can be a few short steps. If you finish this in the next two-three weeks, this can be included in the CHAOSS metrics release.

**Comment by valeriocos** [comment]
Perfect @GeorgLink!

**Comment by inishchith** [comment]
Hi @GeorgLink,
We had started working on License related metrics some time ago. (as you might be aware of through the blog posts) and now are continuously looking for additions and improvements to it. You can find a list of ideas and mock visualizations at https://github.com/inishchith/gsoc-graal/issues/14. and the first iteration of the dashboard can be found at [CoLic-Dashboard](https://grimoirelab-incubator.biterg.io/app/kibana#/dashboard/07dadc50-9c19-11e9-82c4-37956b0c932a)

Please do have a look whenever convenient :)

/cc @valeriocos

**Comment by GeorgLink** [comment]
Thanks for the heads up. I'll take a look.

**Comment by germonprez** [comment]
@GeorgLink does GL provide these visualizations? Would it be worth adding in this next release?

**Comment by GeorgLink** [comment]
Here is the visualization: https://chaoss.github.io/grimoirelab-sigils/panels/colic/

I don't think we have it deployed anywhere

**Comment by germonprez** [comment]
Ok. How do you want to handle this from the GL side of things? If this is still on the roadmap, perhaps we can wait until it is officially deployed.

**Comment by GeorgLink** [comment]
I'm okay either way.
License information in GrimoireLab would only advance with someone in the
community picking it up.
It is not on Bitergia's roadmap.

**Comment by germonprez** [comment]
Sounds good. In an effort to manage issues, I'm going to close this as it appears to have an indefinite end date. Easy enough to reconsider if things change in the future.
