### ISSUE TITLE
Candidate Release Comments (Elephant Factor)

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-risk#15]
This issue was created to collect comments about the upcoming metrics release.

This thread is for comments about Elephant Factor

GitHub location: https://github.com/chaoss/wg-risk/blob/master/metrics/Elephant_Factor.md

Release candidate: https://chaoss.community/metric-elephant-factor

See all release candidates of metrics are at:
https://chaoss.community/metrics-rc/

Important Dates

Release Freeze: June 21st, 2019
Candidate Release: June 24th, 2019
Comments Close: July 24th, 2019
Release Date: August 1st, 2019

**Comment by sgoggins** [comment]
@GeorgLink : We could use a higher resolution image for the Elephant Factor graphic in risk metrics.  We are using a Bitergia example and its a little low resolution.

**Comment by germonprez** [comment]
A few clunky sentences: 

For example, one common filter is to say the elephant factor is to say 50% of the commits are performed by n companies and that is the elephant factor. 

A company evaluating open source software products might use an elephant factor to compare how dependent each projects is on a small set of corporate contributors.

**Comment by foundjem** [comment]
Stackalytics[1] also implement this metric. Also, it is important if we can talk about join collaboration here. For example git has the co-authored-by trailer, etc. 

1. https://www.stackalytics.com/

**Comment by GeorgLink** [comment]
The comment period has ended. Changes have been made. Closing issue.
