### ISSUE TITLE
Candidate Release Comments (Committers)

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-risk#16]
This issue was created to collect comments about the upcoming metrics release.

This thread is for comments about Committers

GitHub location: https://github.com/chaoss/wg-risk/blob/master/metrics/Committers.md

Release candidate: https://chaoss.community/metric-committers

See all release candidates of metrics are at:
https://chaoss.community/metrics-rc/

Important Dates

Release Freeze: June 21st, 2019
Candidate Release: June 24th, 2019
Comments Close: July 24th, 2019
Release Date: August 1st, 2019

**Comment by germonprez** [comment]
LGTM. Nicely done.

**Comment by foundjem** [comment]
Looks good to me.

**Comment by Nebrethar** [comment]
"number of committers = distinct contributor ids over a time period" under Formula:

Quick request for more description on this formula (how it is presented).
