### ISSUE TITLE
Candidate Release Comments (License Declared)

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-risk#19]
This issue was created to collect comments about the upcoming metrics release.

This thread is for comments about License Declared

GitHub location: https://github.com/chaoss/wg-risk/blob/master/metrics/License_Declared.md

Release candidate: https://chaoss.community/metric-license-declared

See all release candidates of metrics are at:
https://chaoss.community/metrics-rc/

Important Dates

Release Freeze: June 21st, 2019
Candidate Release: June 24th, 2019
Comments Close: July 24th, 2019
Release Date: August 1st, 2019

**Comment by germonprez** [comment]
For the SQL, should it be 'license declared' and not 'license concluded'? In SPDX, the former is what is used for the machine (i.e., nomos) identification of licenses.

**Comment by sgoggins** [comment]
@germonprez : I will verify that with @Nebrethar ... when i looked at what is getting populated I thought "concluded" was more clear ...

**Comment by GeorgLink** [comment]
The comment period has ended. Changes have been made. Closing issue.
