### ISSUE TITLE
Require DCO for commits

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-risk#2]
As this is a new repository, I activated the [protobot/dco](https://github.com/apps/dco) bot to check that all commits have a sign-off. The CHAOSS Project Charter requires that all contributions are signed-off. 

For users of the git command line interface, a sign-off is accomplished with the `-s` as part of the commit command: `git commit -s -m 'This is a commit message'`

For users of the GitHub interface, a sign-off is accomplished by writing `Signed-off-by: Your Name <YourName@example.org>` into the commit comment field. This can be automated by using a browser plugin like [scottrigby/dco-gh-ui](https://github.com/)

**Comment by Nebrethar** [comment]
Requested via Probot for this repo

**Comment by germonprez** [comment]
This is done
