### ISSUE TITLE
Candidate Release Comments (Bill of Materials)

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-risk#20]
This issue was created to collect comments about the upcoming metrics release.

This thread is for comments about Bill of Materials

GitHub location: https://github.com/chaoss/wg-risk/blob/master/metrics/Software_Bill_of_Materials.md

Release candidate: https://chaoss.community/metric-bill-of-materials

See all release candidates of metrics are at:
https://chaoss.community/metrics-rc/

Important Dates

Release Freeze: June 21st, 2019
Candidate Release: June 24th, 2019
Comments Close: July 24th, 2019
Release Date: August 1st, 2019

**Comment by germonprez** [comment]
Remove text in Test Cases

**Comment by sgoggins** [comment]
We will update the DOSOCSv2 source repository with @Nebrethar 's updates prior to release.

**Comment by sgoggins** [comment]
NTIA SBOM should be added as a reference.

**Comment by GeorgLink** [comment]
The comment period has ended. Changes have been made. Closing issue.
