### ISSUE TITLE
Metrics Candidate Release tag

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-risk#21]
@sgoggins 

Please create a "Metrics Candidate Release" tag that matches the wording and color from the other work groups.

Here is an example:
https://github.com/chaoss/wg-evolution/issues/189

**Comment by GeorgLink** [comment]
Done. Label created: https://github.com/chaoss/wg-risk/labels/Metrics%20Candidate%20Release

**Comment by klumb** [comment]
Thanks
