### ISSUE TITLE
Candidate Release Comments (Test Coverage)

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-risk#23]
This issue was created to collect comments about the upcoming metrics release.

This thread is for comments about Test Coverage

GitHub location: https://github.com/chaoss/wg-risk/blob/master/metrics/Test_Coverage.md

Release candidate: https://chaoss.community/metric-test-coverage

See all release candidates of metrics are at:
https://chaoss.community/metrics-rc/

Important Dates

Release Freeze: June 21st, 2019
Candidate Release: June 24th, 2019
Comments Close: July 24th, 2019
Release Date: August 1st, 2019

**Comment by sgoggins** [comment]
The metric definition would benefit from examples using a few projects to illustrate test coverage metrics. So, run test coverage tools on 2-3 projects and illustrate the output.

**Comment by germonprez** [comment]
This should be rewritten as a statement: How much of a given code base is covered by at least one test suite.

**Comment by foundjem** [comment]
A good test courage might control for code quality, moreover, a machine learning model can be trained  to suggest areas that need more coverage.
