### ISSUE TITLE
Add GrimoireLab known implementation details to Business Risk metrics

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-risk#25]
This issue is about adding more description to the two Business Risk metrics that will be included in the release:

* Elephant Factor
* Committers

I think that GrimoireLab provides these metrics and it would be great to describe under the section Known Implementations in each metric, how exactly to get the metric within GrimoireLab. I'm thinking a similar description to what we included in the Evolution Metrics, e.g. on [Code Lines Changed](https://github.com/chaoss/wg-evolution/blob/master/metrics/Code_Changes_Lines.md#known-implementations)

/cc @alpgarcia you are an expert on where to find metrics in GrimoireLab. If you don't have time to create a pull request, I can. Could you then point me to a Sigil panel that includes these metrics.

**Comment by alpgarcia** [comment]
About the `Elephant Factor`, we do not have it as a number. What we have are pie charts showing commits by organization. You need to manually calculate the number, e.g.:

![donut-ors-hover](https://user-images.githubusercontent.com/3502941/60244577-f697e700-98ba-11e9-836b-3d9ac31deca4.png)
From: https://chaoss.biterg.io/app/kibana#/dashboard/Overview

If we parametrize the elephant factor for Git contributions at 50%, then it is easy to know that is 1. I'd say it is usually easy to get the Elephant Factor from that charts. Another example for GitHub issues:
https://chaoss.biterg.io/app/kibana#/dashboard/GitHub-Issues

It would be nice to have @jgbarah's view of this too.

-----

About `Commiters`, we directly have the number in evolution (sliced by time units) and in total (for the complete time range selected at the top right time picker) at Git panel:
![Captura de pantalla de 2019-06-27 09-21-10](https://user-images.githubusercontent.com/3502941/60245479-f8fb4080-98bc-11e9-83cd-951a93ef4bf1.png)

![Captura de pantalla de 2019-06-27 09-17-55](https://user-images.githubusercontent.com/3502941/60245332-ade12d80-98bc-11e9-99e1-9e94582ffc76.png)
https://chaoss.biterg.io/app/kibana#/dashboard/Git
From: https://chaoss.biterg.io/app/kibana#/dashboard/Git

Hope it helps!

**Comment by klumb** [comment]
@GeorgLink do you want this added to the upcoming release?

**Comment by GeorgLink** [comment]
Thanks for the ping. I'll create a pull request later today

**Comment by GeorgLink** [comment]
@klumb I created two pr's, one for each metric: #40 and #41
