### ISSUE TITLE
License Selection

### ISSUE THREAD

**Issue by Nebrethar** [chaoss/wg-risk#3]
What license do we plan to use for this repo? I noticed D&I uses GPL and GMD has MIT license

**Comment by germonprez** [comment]
I would suspect MIT based on the Charter as this will be documents

**Comment by Nebrethar** [comment]
Thanks for the input. MIT is proposed in a PR

**Comment by GeorgLink** [comment]
Yes, [CHAOSS Charter section 8.2.3](https://chaoss.community/about/charter/#user-content-8-intellectual-property-policy) requires MIT for metrics.

**Comment by germonprez** [comment]
Done.
