### ISSUE TITLE
Copy editing and standardizing release 

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-risk#42]
Elephant Factor - removed "to be done" on reference implementation 

general edits made -

moved formula into Description to standardize release across wg

merging examples with known implementations

**Comment by klumb** [comment]
Removed numbers from headers

**Comment by klumb** [comment]
To be clear, these changes were made by Matt and myself.

I created the issue for transparency purposes.

**Comment by tharun143** [comment]
@klumb I would like to know more about this issue and want to contribute to it. @klumb can you explain to me more about the issue. I would like to learn more about the Elephant factor and what it is?

**Comment by germonprez** [comment]
Hi @tharun143 -- The metric is posted here: 

https://chaoss.community/metric-elephant-factor/

You can get some more information about the metric that way.

**Comment by klumb** [comment]
I think this is an old issue that needs to be closed. This work was done as part of the first metrics release. 

Thanks @tharun143
