### ISSUE TITLE
Add README to focus-area folder

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-risk#45]
It would be great to have a README in the [focus-area folder](https://github.com/chaoss/wg-risk/tree/master/focus-areas) for better navigation and to show the goals of each focus area.

This is what it looks like in the D&I Working Group:
https://github.com/chaoss/wg-diversity-inclusion/tree/master/focus-areas

**Comment by vchrombie** [comment]
Can I take up this?

**Comment by germonprez** [comment]
Certainly. Thanks @vchrombie
