### ISSUE TITLE
Wrong formula for Elephant Factor? 

### ISSUE THREAD

**Issue by alpgarcia** [chaoss/wg-risk#46]
Looking at the description of this metric I'd say the formula is not correct.

https://github.com/chaoss/wg-risk/blob/e7cea7034d65c65a3658d16a434b9868e52b2306/metrics/Elephant_Factor.md#L5-L9

https://github.com/chaoss/wg-risk/blob/e7cea7034d65c65a3658d16a434b9868e52b2306/metrics/Elephant_Factor.md#L10-L22

As far as I understand, the description is correct while the formula is calculating a different thing. If we had the following companies and commits:

Company | Commits
---|---
A | 1
B | 2
C | 3
D | 4
E | 100

It's clear to me that the EF should be 1 (E) because is contributing more than 50% of commits (if we parametrize EF to that percentage, of course). This results from ordering companies by number of commits (E, D, C, B, A) and start adding commits from the one with more commits (E) until reaching the 50% of total contributions.

So, 50% of total contributions is `(100 + 4 + 3 + 2 + 1) * 0.5 = 55` and once we add commits made by E company we already reach the threshold (`100 > 55`), so EF is 1.

Following the formula, the median would be 3 and the EF would be 2 (D and E), when D is clearly not involved in the higher 50% of contributions.

**Comment by GeorgLink** [comment]
I agree that the formula is wrong. The description is correct. The formula describes how to get 1/2 of all contributing organizations, not the Elephant Factor.

**Comment by foundjem** [comment]
Hello @alpgarcia, thanks for spotting out the error. Your rationale looks good to me, can you also state an arbitrary equation for computing the EF with any given company and commits? To make things consistent.

Signed-Of-By: Armstrong <foundjem@ieee.org>

**Comment by alpgarcia** [comment]
@foundjem did you see my PR (https://github.com/chaoss/wg-risk/pull/101)?

I included the way of computing it step by step. 

Please feel free to review it! :)

**Comment by germonprez** [comment]
Fixed via #101
