### ISSUE TITLE
License Clarity metric from ClearlyDefined

### ISSUE THREAD

**Issue by GeorgLink** [chaoss/wg-risk#72]
The ClearlyDefined project defined a "License Clarity" metric, that we can incorporate in CHAOSS. 

https://github.com/clearlydefined/license-score/blob/master/ClearlyLicensedMetrics.md  

I would not copy this design page 1-to-1, but create a short summary to be included in CHAOSS and then link for the implementation details to ClearlyDefined.

**Comment by germonprez** [comment]
Closing as capturing now in #111
