### ISSUE TITLE
Release Candidate Comments (Elephant Factor)

### ISSUE THREAD

**Issue by germonprez** [chaoss/wg-risk#74]
This issue was created to collect comments about the upcoming metrics release.

**This thread is for comments about Elephant Factor**

GitHub location: https://github.com/chaoss/wg-risk/blob/master/metrics/Elephant_Factor.md

See all release candidates of metrics are at:
https://chaoss.community/metrics-202001/

**Comment by germonprez** [comment]
Include timescale as a filter

**Comment by kestewart** [comment]
FIx "parameterized filter" to be percentage of contribution as well.

**Comment by klumb** [comment]
LGTM

**Comment by klumb** [comment]
Did PR #85 resolve all comments? 

Is this metric ready for release?

**Comment by sgoggins** [comment]
@klumb : This metric is ready for release.

**Comment by klumb** [comment]
I am marking this metric as ready for release and closing. Please reopen if that is not the case.
