### ISSUE TITLE
Release Candidate Comments (Test Coverage)

### ISSUE THREAD

**Issue by germonprez** [chaoss/wg-risk#75]
This issue was created to collect comments about the upcoming metrics release.

**This thread is for comments about Test Coverage**

GitHub location: https://github.com/chaoss/wg-risk/blob/master/metrics/Test_Coverage.md

See all release candidates of metrics are at:
https://chaoss.community/metrics-202001/

**Comment by tommens** [comment]
The section "Objectives" for this "Test Coverage" metric seems out of place. Its description does not really explain the objectives of the metric. It is very different in style and contents compared to the Objectives sections of the other metrics in the 202001 metrics release.
I would expect to see something along the following lines:
"The objective of the Test Coverage metric is to quantitatively assess the extent to which the code base is tested. It is important to note, however, that a high test coverage is by no means a guarantee for high code quality. Test coverage makes no assessment of the effectiveness of the tests."
If needed, some references could be added (there are many available on the web), such as for example https://www.stickyminds.com/article/100-percent-unit-test-coverage-not-enough

**Comment by germonprez** [comment]
Thanks @tommens. The objectives sure do seem off :) 

@sgoggins could you take a look and see if something was not copied over correctly from the Google doc. If that's not the issue, what do you think of the proposed change?

**Comment by sgoggins** [comment]
@tommens and @germonprez : That looks like draft language that got through our edits. At one point it was a more fully described example. Instead of replacing the old, longer example, I put in a short description of the objectives in more general terms. Let me know what you think.

**Comment by kestewart** [comment]
From  "Open source code coverage tools for common languages like Java, C, and C++ are available **from my sites**, including this one."     Fix reference to "from my sites".     Would like to see sample implementations.   Image does explain visualizations - like the others.

**Comment by germonprez** [comment]
Remove the data model and provide a description of the visualization

**Comment by germonprez** [comment]
C, Java, and Python could be the first candidates for deployment

**Comment by klumb** [comment]
Is this metric ready for release?

**Comment by sgoggins** [comment]
I am addressing this now.

**Comment by sgoggins** [comment]
@klumb : Ready for release.

**Comment by klumb** [comment]
I am marking this metric as ready for release and closing. Please reopen if that is not the case.
