### ISSUE TITLE
Release Candidate Comments (License Count)

### ISSUE THREAD

**Issue by germonprez** [chaoss/wg-risk#76]
This issue was created to collect comments about the upcoming metrics release.

**This thread is for comments about License Count**

GitHub location: https://github.com/chaoss/wg-risk/blob/master/metrics/License_Count.md

See all release candidates of metrics are at:
https://chaoss.community/metrics-202001/

**Comment by germonprez** [comment]
Remove the '8' on references 

8. References

**Comment by kestewart** [comment]
This is redundant with the other ones,  not seeing strong value for providing this at this time.

**Comment by germonprez** [comment]
Could be used as a filter in other License-related metrics. Suggest to not include in the next release.

**Comment by klumb** [comment]
Is this metric ready for release?

**Comment by sgoggins** [comment]
@klumb We are not going ot release this metric. we will implement it as a filter on the more broadly construed license enumeration metric in a future release.

**Comment by klumb** [comment]
Thanks!

Okay, I am leaving it open.

**Comment by germonprez** [comment]
@sgoggins is this now an appropriate filter in other metrics?

**Comment by GeorgLink** [comment]
Yes, license count is included in metric `Licenses Declared`.
