### ISSUE TITLE
Release Candidate Comments (License Coverage)

### ISSUE THREAD

**Issue by germonprez** [chaoss/wg-risk#77]
This issue was created to collect comments about the upcoming metrics release.

**This thread is for comments about License Coverage**

GitHub location: https://github.com/chaoss/wg-risk/blob/master/metrics/License_Coverage.md

See all release candidates of metrics are at:
https://chaoss.community/metrics-202001/

**Comment by kestewart** [comment]
Add clarification that the licenses recognized are based on what the scanners can extract.

**Comment by klumb** [comment]
The PR appears to resolve @kestewart comment.

I am marking this metric as ready for release and closing. Please reopen if that is not the case.
