### ISSUE TITLE
Release Candidate Comments (License Declared)

### ISSUE THREAD

**Issue by germonprez** [chaoss/wg-risk#78]
This issue was created to collect comments about the upcoming metrics release.

**This thread is for comments about License Declared**

GitHub location: https://github.com/chaoss/wg-risk/blob/master/metrics/License_Declared.md

See all release candidates of metrics are at:
https://chaoss.community/metrics-202001/

**Comment by germonprez** [comment]
@Nebrethar what is the License Notes column?

**Comment by kestewart** [comment]
Please provide the definition or remove it from this draft.    Rest looks good.

**Comment by klumb** [comment]
Does PR #84 fully address this?

**Comment by klumb** [comment]
Sorry, the above mention is not connected to this metric. It is connected to coverage.

Is this metric ready for release?

**Comment by sgoggins** [comment]
@klumb : reviewing.

**Comment by sgoggins** [comment]
@klumb : Ready for release.

**Comment by klumb** [comment]
I am marking this metric as ready for release and closing. Please reopen if that is not the case.
