### ISSUE TITLE
Release Candidate Comments (OSI Approved LIcenses)

### ISSUE THREAD

**Issue by germonprez** [chaoss/wg-risk#79]
This issue was created to collect comments about the upcoming metrics release.

**This thread is for comments about OSI Approved Licenses**

GitHub location: https://github.com/chaoss/wg-risk/blob/master/metrics/OSI_Approved_Licenses.md

See all release candidates of metrics are at:
https://chaoss.community/metrics-202001/

**Comment by kestewart** [comment]
Reviewed, and with addition of sentence discussed in the meeting,  looks good to me.

**Comment by klumb** [comment]
I am marking this as ready for release and closing. Please reopen if that is not the case.
