### ISSUE TITLE
Release Candidate Comments (CII Best Practices Badge)

### ISSUE THREAD

**Issue by germonprez** [chaoss/wg-risk#80]
This issue was created to collect comments about the upcoming metrics release.

**This thread is for comments about CII Best Practices Badge**

GitHub location: https://github.com/chaoss/wg-risk/blob/master/metrics/CII_Best_Practices.md

See all release candidates of metrics are at:
https://chaoss.community/metrics-202001/

**Comment by germonprez** [comment]
'Resources' should be 'References'

**Comment by sgoggins** [comment]
Fixed.

**Comment by kestewart** [comment]
Looks good to me.

**Comment by klumb** [comment]
I am marking this as ready to release and closing the issue. Please reopen if that is not the case.
