### ISSUE TITLE
Release Notes (risk)

### ISSUE THREAD

**Issue by klumb** [chaoss/wg-risk#81]
Please leave comments and notes here to help construct the release notes document.

**Comment by germonprez** [comment]
@sgoggins could you provide some insight on changes in Risk for this release: 

Any focus area restructuring? 
New metrics for this release? 
Any other big changes?

**Comment by germonprez** [comment]
@sgoggins could you provide a bit of insight here? I need these notes for the next metrics release.

**Comment by sgoggins** [comment]
@germonprez yep. Coming right up!

**Comment by sgoggins** [comment]
# January 2020 Risk Working Group Release Notes
This release focuses on increasing metrics coverage in the general areas of CNCF Core Infrastructure badging and licensing.  The risk working group released the following new metrics, in addition to those released in July, 2019.
1. OSI Approved Licenses
2. Licenses Declared
3. Test Coverage (Update)
4. Elephant Factor
5. Committers 

All Metrics were also restructured slightly to conform to the CHAOSS Project metrics document structure.

**Comment by germonprez** [comment]
Thanks
