### ISSUE TITLE
Asia Pacific Meeting

### ISSUE THREAD

**Issue by germonprez** [chaoss/wg-risk#92]
Hi @king-gao I don't know your email address so I'll ping you here on GH. Could you give me a few times that could work on your end to which we could set-up a CHAOSS meeting for you and some colleagues? Thanks!

**Comment by GeorgLink** [comment]
Michelle Mannering from Australia may also be interested in such a meeting.

**Comment by king-gao** [comment]
Dear Matt and Georg:

Thank you for contact me. My email is king.gao@huawei.com<mailto:king.gao@huawei.com> , you can direct connect me by this address.

Please give me some time, I will ask my college,some universities , other Chinese companies and organizations. I will cocrdinate their schedule and consider your time☺

PS: I must make sure your time is American pacific time, is that right?

Best
King

发件人: Matt Germonprez [mailto:notifications@github.com]
发送时间: 2020年4月1日 2:49
收件人: chaoss/wg-risk <wg-risk@noreply.github.com>
抄送: Gaokun (King) <king.gao@huawei.com>; Mention <mention@noreply.github.com>
主题: [chaoss/wg-risk] Asia Pacific Meeting (#92)


Hi @king-gao<https://github.com/king-gao> I don't know your email address so I'll ping you here on GH. Could you give me a few times that could work on your end to which we could set-up a CHAOSS meeting for you and some colleagues? Thanks!

**Comment by germonprez** [comment]
Certainly! I'll send you an email.

**Comment by king-gao** [comment]
After twice meeting and we adjust the time to fit more and more person:
The Asia Pacific Meeting new schedule is bi-weekly Wednesday: next meeting is May 6 at 8am US Central // 1pm UTC // 9pm in Beijing.

**Comment by GeorgLink** [comment]
That's great. Are you using the CHAOSS Zoom room or meeting elsewhere?

**Comment by germonprez** [comment]
I was going to bring this up in the community call today and then send the announcement. 

Hi everyone, 

I wanted to let you know that we will be now have an Asia-Pacific CHAOSS Community Call. Details for the call are here: 

WednesdaysEvery Two Weeks
8am US Central // 1pm UTC // 9pm in Beijing - Singapore 
Next Meeting: May 6, 2020Connection Details: Same as all CHAOSS calls 
https://unomaha.zoom.us/j/720431288

Topics to consider: 
- CHAOSScon in Asia-Pacific region
- Language translation of CHAOSS documentation- CHAOSS software and working group metrics 

The call is open to all with an interest. Thanks to everyone who pushed to make this happen!
Regards,
Matt

**Comment by king-gao** [comment]
> That's great. Are you using the CHAOSS Zoom room or meeting elsewhere?

hi Georg.,
Of course , we can you zoom ,and  thanks Matt book the meeting source.
May be the guys who from Australia,Japan,Korean can join us together:)

**Comment by king-gao** [comment]
Hi everyone：

Welcome to join Asia-Pacific CHAOSS Community Call tomorrow. The meeting link is in Matt’s email.

If you have any topic to discuss, please send me a email.

Regards
King

发件人: Matt Germonprez [mailto:notifications@github.com]
发送时间: 2020年4月28日 22:05
收件人: chaoss/wg-risk <wg-risk@noreply.github.com>
抄送: Gaokun (King) <king.gao@huawei.com>; Mention <mention@noreply.github.com>
主题: Re: [chaoss/wg-risk] Asia Pacific Meeting (#92)


I was going to bring this up in the community call today and then send the announcement.

Hi everyone,

I wanted to let you know that we will be now have an Asia-Pacific CHAOSS Community Call. Details for the call are here:

WednesdaysEvery Two Weeks
8am US Central // 1pm UTC // 9pm in Beijing - Singapore
Next Meeting: May 6, 2020Connection Details: Same as all CHAOSS calls
https://unomaha.zoom.us/j/720431288

Topics to consider:

  *   CHAOSScon in Asia-Pacific region
  *   Language translation of CHAOSS documentation- CHAOSS software and working group metrics

The call is open to all with an interest. Thanks to everyone who pushed to make this happen!
Regards,
Matt

**Comment by germonprez** [comment]
Closing this issue as we now have an Asia Pacific call. Thanks everyone!
